# Generated by Django 3.1.7 on 2021-03-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Man'), (False, 'Woman')], default=True, verbose_name='Gender'),
        ),
    ]
