# Generated by Django 3.1.7 on 2021-03-15 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25, verbose_name='Brand')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=60, verbose_name='kateqoriya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=127, verbose_name='Mehsulun adi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Qiymet')),
                ('faiz', models.IntegerField(blank=True, null=True, verbose_name='Endirim Faizi')),
                ('full_title', models.CharField(max_length=255, verbose_name='Mehsulun tam adi')),
                ('description', models.TextField(verbose_name='Melumat')),
                ('main_image', models.ImageField(null=True, upload_to='products_main_images', verbose_name=' Esas Sekil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='product.brands', verbose_name='Brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Mehsul',
                'verbose_name_plural': 'Mehsullar',
            },
        ),
        migrations.CreateModel(
            name='ScreenSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='Ekran olcusu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ekran olcusu',
                'verbose_name_plural': 'Ekran olculeri',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=60, verbose_name='taglar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShortSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_specs', models.CharField(blank=True, max_length=63, null=True, verbose_name='Qisa xususiyyetler')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ManyToManyField(blank=True, db_index=True, null=True, related_name='shortspecs', to='product.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Qisa Xususiyyet',
                'verbose_name_plural': 'Qisa xususiyyetler',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=63, verbose_name='Tam ad')),
                ('email', models.EmailField(max_length=63, verbose_name='Email')),
                ('comment', models.TextField(verbose_name='Rey')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewusers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_reviews', to='product.review', verbose_name='Parent Comment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsreview', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Xususiyyetin adi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(blank=True, db_index=True, null=True, related_name='categoryspec', to='product.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Mehsulun xususiyyet adi',
                'verbose_name_plural': 'ehsulun xususiyyet adlari',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Xusisiyyeti yazin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prod_spec_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_names', to='product.productspecname', verbose_name='Product Spec Name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productnames', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Mehsulun xususiyyeti',
                'verbose_name_plural': 'ehsulun xususiyyetleri',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='screensize',
            field=models.ManyToManyField(db_index=True, related_name='screensizes', to='product.ScreenSize', verbose_name='ScreenSize'),
        ),
        migrations.AddField(
            model_name='product',
            name='taglar',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='taglar', to='product.Tag', verbose_name='Taglar'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='Sekil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimages', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Sekil',
                'verbose_name_plural': 'Sekiller',
            },
        ),
    ]
