# Generated by Django 3.1.7 on 2021-03-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='types_az',
            field=models.CharField(max_length=60, null=True, verbose_name='kateqoriya'),
        ),
        migrations.AddField(
            model_name='category',
            name='types_en',
            field=models.CharField(max_length=60, null=True, verbose_name='kateqoriya'),
        ),
    ]
