# Generated by Django 3.1.7 on 2021-04-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
